version: '3.7'
services:
  nginx:
    build: ./docker-cmdb/nginx
    restart: always
    volumes:
      - type: bind
        source: ./docker-cmdb/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./docker-cmdb/nginx/allstatic
        target: /allstatic
    networks:
      - jumpserver-test
    ports:
      - "80:80"
    tty: true
    container_name: "nginx_server"
        
